### ISSUE TITLE
Support some HTML and markup formatting in the model text

### ISSUE THREAD

**Issue by ebrob** [ebrob/AntiShaun#2]
The user might want to format the text string within the model -- this could be done by embedding basic HTML formatting (`<b>`, `<i>` tags, etc.) or using something like [Markdown](http://en.wikipedia.org/wiki/Markdown).

Idea from [XDocReport FAQ](https://code.google.com/p/xdocreport/wiki/FAQ).

**Comment by Calvinfs852** [comment]
Looking into supporting Markdown or Markdown-like syntax. Since the documents are being created and displayed via LibreOffice, either the text in the model needs LibreOffice markup in it or our own flavor or markup that I can tell AntiShaun to convert to LibreOffice markup. Either way, seems doable: will start working on this in the near future.

**Comment by ghost** [comment]
This might be a possibility - http://commonmark.org/
